CREATE TABLE post
(
    id IDENTITY,
    slug      VARCHAR(100) NOT NULL UNIQUE,
    author    VARCHAR(100) NOT NULL,
    title     VARCHAR(255) NOT NULL,
    perex     TEXT         NOT NULL,
    body      TEXT         NOT NULL,
    published DATE
);

CREATE
    INDEX ON post(published);

INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('cesta-na-sicilii', 'Šárka Klauberová', 'Moje cesta na Sicilii', '<p>Poznejte krásy <strong>Sicílie</strong> očima cestovatelky, která miluje moře, památky a dobré jídlo.</p>', '<h2>Úvod</h2>
  <p>Letní dobrodružství mě letos zavedlo na ostrov Sicílie, kde jsem poprvé navštívila městečko <strong>Taormina</strong> s úchvatným výhledem na Etnu.</p>
  <h3>Tipy na výlety</h3>
  <ul>
    <li>Výstup k <strong>sopce Etna</strong></li>
    <li>Procházka historickou částí <em>Siracusy</em></li>
    <li>Koupání u pláže <strong>San Vito Lo Capo</strong></li>
  </ul>
  <h3>Gastronomie</h3>
  <p>Místní kuchyně je naprosto skvělá – doporučuji jejich <strong>granitu</strong> a čerstvé ryby. Skvělé jsou i trhy s ovocem v Catanii.</p>
  <h3>Závěr</h3>
  <p>Sicílie nabízí nejen památky a přírodu, ale také přátelské místní a pohodovou atmosféru k odpočinku.</p>', '2025-11-30');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('vikend-v-parizi', 'Tomáš Hrubý ', 'Víkend v Paříži', '<p>Co všechno stihnete za <b>jeden víkend</b> v Paříži? Inspirujte se mým itinerářem a tipy.</p>', '<h2>1. den: Klasika i moderní Paříž</h2>
  <p>Začal jsem výšlapem na <a href="https://eiffelovka.com">Eiffelovu věž</a>, po obědě návštěva Louvru a večer tradiční <em>bageta</em> u Seiny.</p>
  <h2>2. den: Umělecká atmosféra</h2>
  <p>Prošel jsem si čtvrť <strong>Montmartre</strong> – kavárny, ateliéry a slavný Sacré-Cœur. Velmi doporučuji piknik ve <i>výhledu na město</i>.</p>
  <h2>Praktické rady</h2>
  <ul>
    <li>Využijte <strong>sdílená kola</strong> – jsou rychlá a levná</li>
    <li>Rezervujte vstupy předem – ušetříte hodiny čekání</li>
  </ul>', '2025-11-07');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('pesi-tura-ceske-svycarsko', 'Eva Řídká', 'Pěší tura Českým Švýcarskem', '<p>Moje tipy na nejlepší trasy, <strong>ubytování</strong> a zážitky z nejkrásnější oblasti Česka.</p>', '<h2>Nejoblíbenější trasa: Hřensko – Pravčická brána</h2>
  <p>Začínám vždy v <b>Hřensku</b> a přes Soutěsky mířím k Pravčické bráně. Po cestě <em>přístřešky</em> pro odpočinek a úchvatné výhledy.</p>
  <h3>Ubytování</h3>
  <p>Doporučuji útulný penzion <strong>U Lípy</strong> v Mezní Louce, kde vaří i tradiční borůvkové knedlíky.</p>
  <h3>Zajímavosti</h3>
  <ul>
    <li>Zubrnice – <i>železniční skanzen</i></li>
    <li>Děčínský Sněžník – rozhledna se skvělým rozhledem</li>
  </ul>
  <p>Ideální pro rodinné i sólo výlety.</p>', '2025-07-09');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('evropa-vlakem', 'Petr Malina', 'Křížem krážem Evropou vlakem', '<p>Cestování vlakem po Evropě má svůj půvab – <strong>slow travel</strong> vám umožní poznat lokální kulturu i přírodu.</p>', '<h2>Plán cesty</h2>
  <p>Během tří týdnů jsem projel s Interrail jízdenkou 8 zemí: Itálie, Francie, Švýcarsko, Německo, Rakousko… Nejvíc mě nadchlo <strong>Toskánsko a švýcarské Alpy</strong>.</p>
  <h3>Tipy na trasy</h3>
  <ul>
    <li>Curych – Milán: Trasa přes Alpy</li>
    <li>Florencie – Benátky: Romantika vlakem</li>
    <li>Paříž – Amsterdam: Ideální na city breaky</li>
  </ul>
  <h3>Praktické poznámky</h3>
  <p>Používejte aplikaci Deutsche Bahn pro rychlé hledání přestupů a návazností.</p>
  <h2>Závěrečné doporučení</h2>
  <p>Cestování vlakem je ekologické, pohodlné a otvírá nové pohledy na Evropu.</p>', '2025-08-22');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('dovolena-na-lipne', 'Lenka Stará', 'Letní dovolená na Lipně s dětmi', '<p>Jak naplánovat relax i zábavu na Lipně, když cestujete s malými <strong>dětmi</strong>?</p>', '<h2>Kam vyrazit s dětmi</h2>
  <p>Nejoblíbenější je <strong>Stezka korunami stromů</strong>, kde si děti užijí i adrenalinový tobogán. Dalším skvělým cílem je <i>Aquaworld Lipno</i>.</p>
  <h3>Ubytování</h3>
  <p>Volili jsme apartmán přímo u jezera s vlastní kuchyňkou. Výhodou je blízkost cyklostezky a dětského hřiště.</p>
  <h3>Tipy na výlety</h3>
  <ul>
    <li>Půjčení koloběžek na hrázi</li>
    <li>Vyhlídková plavba lodí po Lipně</li>
  </ul>
  <h3>Stravování</h3>
  <p>V okolí je spousta restaurací s dětskými koutky a možností domácích polévek.</p>
  <h2>Závěr</h2>
  <p>Lipno doporučuji pro klidnou dovolenou ve spojení s přírodou, zázemím pro děti a možností cyklistiky i koupání.</p>', '2025-06-12');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('turistika-s-batoletem', 'Barbora Krejčová', 'Turistika s batoletem v Jeseníkách', '<p>Na co si dát pozor a jak si <strong>turistiku s malým dítětem</strong> opravdu užít?</p>', '<h2>Plánování trasy</h2>
  <p>Kratší nenáročné trasy, např. kolem <b>Karlovy Studánky</b> nebo k Pradědu s možností přebalit dítě na odpočívadle.</p>
  <h3>Vybavení</h3>
  <ul>
    <li>Ergonomické nosítko</li>
    <li>Deka pro piknik i hraní</li>
    <li>Praktická svačina (fruity, kaše do kapsičky)</li>
  </ul>
  <h3>Přestávky a zážitky</h3>
  <p>Dopřejte si čas na hřištích i krátké průzkumy přírody s dětmi – objevování kačenek v potůčku nebo šišek v lese.</p>
  <h3>Závěr</h3>
  <p>Nebojte se cestovat ani s batoletem, hlavní je pohoda a přizpůsobení tempa možnostem dítěte.</p>', '2025-05-15');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('zimni-alpy-2025', 'Martin Beránek', 'Zimní dobrodružství v Alpách 2025', '<p>Objevte ty nejlepší <b>lyžařské areály</b> Rakouska a Itálie pro pestře strávenou zimní <strong>dovolenou</strong>.</p>', '<h2>Kde lyžovat</h2>
  <ul>
    <li>Sölden – rozmanité terény a noční sáňkování</li>
    <li>Livigno – perfektní snowparky a duty free nákupy</li>
    <li>Stubai – ledovec s celoročním provozem</li>
  </ul>
  <h3>Ubytování a služby</h3>
  <p>Moderní hotely i tradiční apartmány, wellness zóny a skvělé půjčovny vybavení.</p>
  <h3>Tipy na zážitky</h3>
  <p>Kromě lyžování zkuste i večerní procházky nebo ochutnávky místních sýrů.</p>
  <h3>Závěr</h3>
  <p>Alpy v zimě potěší sportovce i rodiny – každý si najde svůj program.</p>', '2025-01-05');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('cestovani-italie-rim', 'Lucie Nováková', 'Průvodce po Římě: Objevte věčné město', '<p>Řím je jedním z <strong>nejkrásnějších měst</strong> na světě. Přijďte se podívat na <em>Koloseum</em>, <em>Vatikán</em> a <em>Fontánu di Trevi</em>.</p>', '<h2>Úvod do Říma</h2><p>Řím je plný <strong>historie a umění</strong>. Každý roh města skrývá něco úžasného.</p><h3>Nejlepší místa k návštěvě</h3><ul><li>Koloseum</li><li>Vatikán a Svatopetrův chrám</li><li>Fontána di Trevi</li><li>Římské fórum</li></ul><p>Skvělý čas na návštěvu je <strong>březen až květen</strong>, kdy je počasí krásné a není příliš horko. V tomto období se vyhnete i velkému davům turistů.</p>', '2025-08-20');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('domaci-tiramisu-recept', 'Martin Svoboda', 'Jak připravit domácí tiramisu: Tradiční italský recept', '<p>Tiramisu je <strong>snadné na přípravu</strong> a <em>neuvěřitelně chutné</em>. Tentokrát bez pečení!</p>', '<h2>Ingredience</h2><ul><li><strong>250g</strong> mascarpone</li><li><strong>4</strong> vejce</li><li><strong>100g</strong> cukru</li><li><strong>200ml</strong> silné kávy</li><li><strong>30g</strong> kakaa</li><li><strong>24</strong> suchárků (savoiardi)</li></ul><h2>Postup přípravy</h2><ol><li>Oddělte žloutky od bílků</li><li>Vyšlehejte bílky na tuhý sníh</li><li>Žloutky s cukrem vyšlehejte do pěny</li><li>Přidejte mascarpone a jemně zacvakejte</li><li>Ponořte suchárky do kávy a vrstete do formy</li><li>Nechte <strong>přes noc v lednici</strong></li></ol><p>Desert je ideální pro <em>letní večery</em>!</p>', '2025-11-05');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('fitness-trenerka-pro-zacatecniky', 'Jana Kratochvílová', 'Tréninky pro začátečníky: Jak začít s běháním''', '<p>Chcete začít se sportem? <strong>Běhání je ideální</strong> aktivita pro všechny. Zde najdete <em>tipy, jak správně začít</em>.</p>', '<h2>Proč začít s běháním?</h2><p>Běhání je <strong>jeden z nejjednodušších způsobů</strong>, jak se dostat do formy. Nemusíte být vybavení, stačí jen vhodné tenisky a příprava.</p><h2>Tipy pro začátečníky</h2><ul><li>Investujte do <strong>kvalitních tenisek</strong></li><li>Začněte <strong>pomalu</strong> a postupně si zvyšujte zátěž</li><li>Běhejte <strong>3-4x týdně</strong></li><li>Nezapomeňte na <strong>rozcvičení a protažení</strong></li></ul><h2>Jak se vyhnout zraněním</h2><p>Správná <em>technika běhu</em> je klíčová. Dbejte na správné držení těla a nedělajte příliš dlouhé skluzy. Poslechněte si své tělo – pokud bolí, <strong>odpočiňte si</strong>.</p>', '2025-05-06');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('parizska-kava-kultura', 'Sophie Laurent', 'Pařížská kávová kultura: Jak pít kávu jako Francouz', '<p>Káva v Paříži není jen nápoj, je to <strong>rituál a součást života</strong>. Objevte <em>tradice pařížských kaváren</em>.</p>', '<h2>Historie kávoren v Paříži</h2><p>Pařížské kavárny jsou centrem společenského života. Každá má svou <strong>jedinečnou atmosféru</strong> a historii.</p><h2>Jak si objednat kávu</h2><ul><li><strong>Café</strong> – espresso</li><li><strong>Café crème</strong> – espresso s mlékem</li><li><strong>Café au lait</strong> – káva se smetanou</li><li><strong>Noisette</strong> – malá espresso s kapkou mléka</li></ul><p>Nejdůležitější je <em>vychutnat si čas</em> a koukat na průchod lidí!</p>', '2025-10-16');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('domaci-chleb-krok-za-krokem', 'Petr Novotný', 'Pečení domácího chleba: Jednoduchý recept pro začátečníky''', '<p>Domácí chlebek je <strong>čerstvý, chutný a levnější</strong> než z obchodu. Zkuste to doma!</p>', '<h2>Ingredience</h2><ul><li><strong>500g</strong> mouky</li><li><strong>350ml</strong> vody</li><li><strong>10g</strong> soli</li><li><strong>7g</strong> droždí</li></ul><h2>Postup</h2><ol><li>Smíchejte mouku a vodu</li><li>Přidejte droždí a sůl</li><li>Nechte kynout <strong>2 hodiny</strong></li><li>Vytvarujte chlebek a nechte znovu kynout</li><li>Pečte na <strong>220°C po dobu 30 minut</strong></li></ol><p>Výsledek? <em>Úžasný vůně a vláčný chlebek!</em></p>', '2025-12-03');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('nordic-walking-pro-vsechny', 'Markéta Svobodová', 'Nordic walking: Perfektní sport pro všechny věkové skupiny', '<p>Nordic walking je <strong>bezpečný a účinný</strong> způsob, jak zlepšit své zdraví. Vhodný pro <em>všechny věkové kategorie</em>.</p>', '<h2>Co je to Nordic walking?</h2><p>Nordic walking je chůze s <strong>speciálními hůlkami</strong>, která zvyšuje zátěž na horní část těla. Pochází ze <em>Skandinávie</em>.</p><h2>Výhody Nordic walkingu</h2><ul><li>Posiluje <strong>80% svalů těla</strong></li><li>Šetrný na <strong>klouby a záda</strong></li><li>Zlepšuje <strong>kardiovaskulární systém</strong></li><li>Lze provozovat <strong>celoročně</strong></li></ul><h2>Jak začít</h2><p>Stačí si koupit <strong>správné hůlky</strong> a najít si skupinu. Už máš základ!</p>', '2025-11-03');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('vegetarianske-burgery', 'Elena Václavová', 'Zdravé vegetariánské burgery: Recept bez masa', '<p>Vegetariánské burgery mohou být <strong>stejně chutné</strong> jako ty mясné. Naučte se je <em>připravit doma</em>!</p>', '<h2>Ingredience na placky</h2><ul><li><strong>250g</strong> černé čočky</li><li><strong>100g</strong> ořechů (vlašské)</li><li><strong>1</strong> cibule</li><li><strong>2</strong> stroužky česneku</li><li><strong>50g</strong> mouky</li><li><strong>2</strong> vejce</li></ul><h2>Příprava</h2><ol><li>Uvařte čočku a nechte vychladnout</li><li>Ořechy zpracujte na kousky</li><li>Smíchejte všechny ingredience</li><li>Vytvořte placky a smažte na oleji</li><li>Podávejte v bulkách s salátem</li></ol><p>Perfektní pro <strong>rychlý oběd</strong> nebo <em>grilování</em>!</p>', '2025-09-24');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('barcelona-top-10-atrakci', 'Tomáš Hrubý ', 'Barcelona: Top 10 míst, která musíte vidět', '<p>Barcelona je živá a barevná metropole. Zde jsou <strong>nejlepší atrakce</strong>, které nesmíte <em>minout</em>.</p>', '<h2>Top 10 míst v Barceloně</h2><ol><li><strong>Sagrada Família</strong> – nádherný chrám Gaudího</li><li><strong>Park Güell</strong> – kouzelný park s mozaikami</li><li><strong>Casa Batlló</strong> – unikátní palác z roku 1904</li><li><strong>La Rambla</strong> – nejživější ulice ve městě</li><li><strong>Gotická čtvrť</strong> – historické středověké uličky</li><li><strong>Písečná pláž</strong> – relaxace u moře</li><li><strong>Montjuïc</strong> – vrch s krásným výhledem</li><li><strong>Muzeum Picassa</strong> – díla slavného umělce</li><li><strong>Kolumbus památník</strong> – ikonická socha</li><li><strong>Jídlo na tržích</strong> – La Boqueria trh</li></ol><p>Barcelona je <em>město plné energie a kultury</em>!</p>', '2025-10-27');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('interni-design-minimalizmus', 'Šárka Klauberová', 'Minimalistický design domů: Jak vytvořit jednoduchý a elegantní prostor', '<p>Minimalizmus není jen styl, je to <strong>životní filozofie</strong>. Naučte se <em>vytvořit krásný a prostorný domov</em>.</p>', '<h2>Principy minimalismu</h2><ul><li><strong>Méně je více</strong> – odebírejte, co nepotřebujete</li><li><strong>Neutrální barvy</strong> – bílá, šedá, béžová</li><li><strong>Funkčnost</strong> – každý kus má své místo</li><li><strong>Čistota</strong> – pořádek a harmonie</li></ul><h2>Jak začít</h2><ol><li>Vyberte si barvu pozadí</li><li>Investujte do kvalitního nábytku</li><li>Odstraňte zbytečné věci</li><li>Přidejte přírodu – rostliny a dřevo</li><li>Nechte volný prostor na podlaze</li></ol><p>Výsledek? <strong>Klid a harmonie</strong> v každém rohu!</p>', '2025-09-03');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('zdravy-snidane-5-recepty', 'Eva Řídká', 'Zdravý snídaně: 5 jednoduchých receptů pro energický start', '<p>Snídaně je <strong>nejdůležitější jídlo</strong> dne. Zde jsou <em>5 skvělých receptů</em> pro váš start!</p>', '<h2>1. Ovesná kaše s ovocem</h2><p>Jednoduché a <strong>sytící</strong>. Přidejte banán, jahody a med.</p><h2>2. Vejce s avokádem</h2><p>Proteiny + zdravé tuky = <strong>dokonalý start</strong>!</p><h2>3. Jogurt s granolou</h2><p>Krémový, chutný a <strong>plný antioxidantů</strong>.</p><h2>4. Smoothie bowl</h2><p>Lahodné a fotogenické. Украшайте <strong>kokosem a ořechy</strong>.</p><h2>5. Chlebíček s hummusem</h2><p>Rychlé, <em>zdravé a sytící</em>.</p>', '2025-11-04');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('yoga-pro-zacatecniky-doma', 'Elena Václavová', 'Yoga doma: Jednoduchý program pro začátečníky', '<p>Yoga není jen pohyb, je to <strong>meditace v pohybu</strong>. Zkuste ji <em>doma bez vybavení</em>!</p>', '<h2>Proč začít s yogou</h2><ul><li>Zvyšuje <strong>flexibilitu</strong></li><li>Snižuje <strong>stres a úzkost</strong></li><li>Posiluje <strong>střed těla</strong></li><li>Zlepšuje <strong>postoj a rovnováhu</strong></li></ul><h2>Základní pózy pro začátečníky</h2><ol><li><strong>Tadasana</strong> – pozice na stojné</li><li><strong>Downward Dog</strong> – pes hlavou dolů</li><li><strong>Child\''s Pose</strong> – pozice dítěte</li><li><strong>Warrior Pose</strong> – pozice válečníka</li><li><strong>Savasana</strong> – odpočinkový stav</li></ol><p>Cvičte <strong>20-30 minut denně</strong> a cítit budete rozdíl!</p>', '2025-04-17');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('talianske-vino-srovnani', 'Barbora Krejčová', 'Italská vína: Kompletní průvodce pro milovníky vína', '<p>Italská vína jsou <strong>celosvětově slavná</strong>. Poznejte jejich <em>jedinečné chuti a originy</em>.</p>', '<h2>Nejznámější italské regiony</h2><ul><li><strong>Toskánsko</strong> – Chianti, Brunello</li><li><strong>Piemonte</strong> – Barolo, Barbaresco</li><li><strong>Verona</strong> – Amarone, Valpolicella</li><li><strong>Friuli</strong> – bílá vína, Pinot Grigio</li></ul><h2>Jak poznat kvalitní víno</h2><ol><li>Podívejte se na <strong>region a ročník</strong></li><li>Čtěte etiketu a <strong>obsah alkoholu</strong></li><li>Zkuste a <strong>pochutnějte si</strong></li><li>Kupujte z <strong>důvěryhodných zdrojů</strong></li></ol><p>Nejlepší je sdílet víno s <em>přáteli a dobrou jídlem</em>!</p>', '2025-01-14');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('cestovani-senhora-portugal', 'Petr Malina', 'Cestování v Portugalsku: Hidden gems mimo hlavní cesty', '<p>Portugalsko je více než Lisabon a Porto. Objevte <strong>skryté klenoty</strong> a <em>autentickou kulturu</em>.</p>', '<h2>Kam jít mimo turistické trasy</h2><ul><li><strong>Sintra</strong> – kouzelné paláce a lesy</li><li><strong>Pena Palace</strong> – barevný zámek</li><li><strong>Kaskády vody</strong> – přírodní bazény</li><li><strong>Algarve pobřeží</strong> – divoké pláže</li><li><strong>Madeira</strong> – horský ráj</li></ul><h2>Místní jídlo</h2><p>Zkuste <strong>bacalhau à Brás</strong> a <em>pastéis de nata</em>. Úžasné!</p><h2>Praktické tipy</h2><ol><li>Jezděte <strong>mimo sezon</strong> – levněji a méně davů</li><li>Používejte <strong>místní dopravu</strong></li><li>Mluvte s <strong>místními lidmi</strong> o tipech</li></ol>', '2025-06-16');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('grilování-letni-gril-recepty', 'Tomáš Horák', 'Letní grilování: 7 nejlepších receptů na gril', '<p>Grilování je <strong>umění a radost</strong>. Tady jsou <em>recept y na nezapomenutelné</em> léto!</p>', '<h2>Tipy na grilování</h2><ul><li>Zahřejte gril na <strong>vysokou teplotu</strong></li><li>Používejte <strong>kvalitní maso</strong></li><li>Würsty a drůbez nechte <strong>mírně odlehlé</strong></li><li>Nepřesolte – chutí je více</li></ul><h2>7 nejlepších receptů</h2><ol><li><strong>Grilované kuřecí stehna</strong> – měkké a šťavnaté</li><li><strong>Flank steak marinade</strong> – pikantní a chutný</li><li><strong>Pstruh na bylinkách</strong> – delikátní rybka</li><li><strong>Zapečené brambory</strong> – jednoduché sladidlo</li><li><strong>Grilované zelenina</strong> – zeleninový mix</li><li><strong>Kuřecí špízy</strong> – barevné a sytící</li><li><strong>Grilované ananasu</strong> – sladký deser</li></ol><p>Poslední tip: <em>Užijte si sluníčko a přátele!</em></p>', '2025-05-03');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('amsterdam-bicykly-kanaly', 'Barbora Krejčová', 'Amsterdam: Město kol a kanálů', '<p>Amsterdam je <strong>bikový ráj</strong>. Objevte město na <em>vlastním kole</em> a plujte po nádherných kanálech.</p>', '<h2>Proč jezdit na kole v Amsterdamu</h2><ul><li><strong>Bezpečné cyklostezky</strong> všude</li><li><strong>Půjčovna kol</strong> na každém rohu</li><li><strong>Lehké</strong> a rychlé cestování</li><li>Nejekologičtější doprava</li></ul><h2>Musíte vidět</h2><ol><li><strong>Kanály</strong> – UNESCO světové dědictví</li><li><strong>Vondelpark</strong> – největší park</li><li><strong>Anne Frank dům</strong> – historie</li><li><strong>Muzea</strong> – Van Gogh a Rembrandt</li><li><strong>Květinové trhy</strong> – barvité tulipány</li></ol><p>Plavba po kanálech <em>večer je romantická a nádherná</em>!</p>', '2025-02-26');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('domaci-pizza-neapolitanska', 'Petr Novotný', 'Neapolská pizza doma: Jak péci autentickou pizzu', '<p>Pizza z Neapole je <strong>nejlepší na světě</strong>. Naučte se ji <em>péci v domácí troubě</em>!</p>', '<h2>Ingredience na těsto</h2><ul><li><strong>500g</strong> mouky typu 00</li><li><strong>325ml</strong> vody</li><li><strong>10g</strong> soli</li><li><strong>3g</strong> čerstvého droždí</li><li><strong>15ml</strong> olivového oleje</li></ul><h2>Postup</h2><ol><li>Smíchejte vodu a droždí</li><li>Přidejte mouku a sůl postupně</li><li>Hněťte <strong>10 minut</strong> na pracovní ploše</li><li>Nechte kynout <strong>18-24 hodin</strong> v chladnu</li><li>Rozviňte těsto a přidejte náplň</li><li>Pečte na <strong>300°C po dobu 2-3 minut</strong></li></ol><p>Tajemství? <strong>Trpělivost a kvalitní ingredience</strong>!</p>', '2025-11-28');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('pilates-core-posileni', 'Sophie Laurent', 'Pilates: Jak posilovat střed těla a zlepšit postoj', '<p>Pilates je <strong>revoluce v posilování</strong>. Zlepšete <em>flexibilitu, sílu a postoj</em>!</p>', '<h2>Co je pilates</h2><p>Pilates je cvičení zaměřené na <strong>hluboké stabilizační svaly</strong>. Kombinuje <em>sílu, flexibilitu a dech</em>.</p><h2>Top 5 cviků</h2><ol><li><strong>Hundred</strong> – zahřívací cvik</li><li><strong>The Roll Up</strong> – páteř postupně</li><li><strong>Single Leg Circles</strong> – stability nohy</li><li><strong>Rolling Like a Ball</strong> – masáž páteře</li><li><strong>Single Leg Stretch</strong> – brušní svaly</li></ol><h2>Výhody pilates</h2><ul><li>Posiluje <strong>core (střed těla)</strong></li><li>Zlepšuje <strong>postoj a rovnováhu</strong></li><li>Snižuje <strong>bolesti zad</strong></li><li>Zvyšuje <strong>flexibilitu a pohyblivost</strong></li></ul><p>Cvičte <strong>3x týdně po 30-45 minut</strong>!</p>', '2025-11-21');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('vegan-cokolada-dort', 'Veronika Svobodová', 'Veganský čokoládový dort: Bez vajec a mléka', '<p>Veganský dort nemusí být <strong>nudný nebo suchý</strong>. Tento <em>čokoládový dort je jednoduchý a chutný</em>!</p>', '<h2>Ingredience</h2><ul><li><strong>200g</strong> mouky</li><li><strong>50g</strong> kakaa</li><li><strong>200ml</strong> rostlinného mléka</li><li><strong>100ml</strong> oleje</li><li><strong>200g</strong> cukru</li><li><strong>2</strong> lžičky kypřícího prostředku</li><li><strong>1</strong> lžička octa</li></ul><h2>Příprava</h2><ol><li>Smíchejte suché ingredience</li><li>V míse smíchejte rostlinné mléko, olej a ocet</li><li>Spojte obě směsi</li><li>Nalijte do formy</li><li>Pečte na <strong>180°C po dobu 30-35 minut</strong></li></ol><h2>Poleva</h2><p>Připravte jednoduchou <strong>čokoládovou polevu</strong> z kakaa, rostlinného mléka a cukru.</p>', '2025-03-24');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('balaton-jezero-tyzden', 'Veronika Svobodová', 'Jezero Balaton: Dokonalá letní dovolená v Maďarsku', '<p>Balaton je <strong>největší jezero v Evropě</strong>. Ideální destinace pro <em>relaxaci a zábavu</em>!</p>', '<h2>Proč si vybrat Balaton</h2><ul><li><strong>Teplá voda</strong> v létě</li><li><strong>Pláže</strong> pro všechny</li><li><strong>Vinařství</strong> v okolí</li><li><strong>Nádherné malebné vesnice</strong></li><li><strong>Aktivní zábava</strong> (windsurfing, vsailing)</li></ul><h2>Nejlepší místa</h2><ol><li><strong>Siófok</strong> – party destinace</li><li><strong>Tihany</strong> – pronárodní park</li><li><strong>Keszthely</strong> – zámek a vinařství</li><li><strong>Balatonfüred</strong> – elegantní resort</li></ol><h2>Kdy jít</h2><p>Nejlepší je <strong>květen až září</strong>. Voda je nejteplější v <em>červenci a srpnu</em>.</p>', '2025-10-05');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('smoothie-bowls-pestrej', 'Tomáš Horák', 'Smoothie bowls: Pestré a zdravé misky plné vláken', '<p>Smoothie bowls jsou <strong>krásné, zdravé a lákavé</strong>. Zkuste si <em>vytvořit vlastní variantu</em>!</p>', '<h2>Základní recept</h2><ul><li><strong>2</strong> zmrazené banány</li><li><strong>200ml</strong> rostlinného mléka</li><li><strong>100g</strong> zmrazeného ovoce (borůvky, jahody)</li><li><strong>1</strong> polévka arašídového másla</li></ul><h2>Topping - možnosti</h2><ol><li><strong>Granola</strong> – křupavost</li><li><strong>Kokos</strong> – tropická příchuť</li><li><strong>Čerstvé ovoce</strong> – barva a vláken</li><li><strong>Ořechy</strong> – proteiny</li><li><strong>Semínka</li> – zdraví</strong></li><li><strong>Čokoládové chipsy</strong> – sladkost</li><li><strong>Med</strong> – sladidlo</li></ol><h2>Postup</h2><p>Mixem namixujte veškeré ingredience do husté konzistence. Nalijte do misky a ozdobte toppingem. <em>Fotogenické a sytící!</em></p>', '2025-10-29');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('kreta-turecke-more', 'Petr Novotný', 'Kréta: Řecký ostrov s nekonečným sluncem a moří', '<p>Kréta je <strong>největší řecký ostrov</strong>. Kombinuje <em>starobylou kulturu s moderní pohostinností</em>!</p>', '<h2>Nejlepší pláže</h2><ul><li><strong>Balos Laguna</strong> – tyrkysová voda</li><li><strong>Elafonissi</strong> – růžový písek</li><li><strong>Samaria Gorge</strong> – vodopád</li><li><strong>Falassarna</strong> – dlouhá písečná pláž</li></ul><h2>Historie a kultura</h2><ol><li><strong>Knosský palác</strong> – minojská civilizace</li><li><strong>Chania</strong> – staré město s přístaven</li><li><strong>Rethymno</strong> – benátský zámek</li><li><strong>Spinalonga ostrov</strong> – pevnost</li></ol><h2>Místní jídlo</h2><p><strong>Dakos</strong>, <strong>moussaka</strong> a <strong>čerstvá ryba</strong> na grilu. Lahodné!</p>', '2025-09-01');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('trainerka-cviky-bez-vybaveni', 'David Svoboda', 'Cviky bez vybavení: Jak trénovat kdekoliv a kdykoliv', '<p>Nepotřebujete tělocvičnu ani vybavení. <strong>Vlastní tělo stačí</strong> pro <em>efektivní trénink</em>!</p>', '<h2>Top 10 cviků bez vybavení</h2><ol><li><strong>Kliky</strong> – prsní a triceps</li><li><strong>Dřepy</strong> – nohy a hýždě</li><li><strong>Crunch</strong> – brušní svaly</li><li><strong>Plank</strong> – core stabilita</li><li><strong>Burpees</strong> – plný tělo</li><li><strong>Mountain climbers</strong> – kardio</li><li><strong>Lunges</strong> – nohavice a rovnováha</li><li><strong>Push-up variace</strong> – různé úrovně</li><li><strong>Skákání</strong> – kardio energie</li><li><strong>Deska na boku</strong> – boční core</li></ol><h2>Trénink</h2><p>Proveďte <strong>3 série po 15 opakování</strong> bez přestávky. <em>Hýbejte se!</em></p>', '2025-09-30');
INSERT INTO PUBLIC.POST (SLUG, AUTHOR, TITLE, PEREX, BODY, PUBLISHED) VALUES ('rakousko-alpske-klenoty', 'Elena Václavová', 'Rakousko: Procházka alpskými skvostů a vídeňskou elegancí', '<p>Rakousko je <strong>země hudby, kultury a hor</strong>. Objev <em>malebné vesnice a velkolepou architekturu</em>!</p>', '<h2>Řeší jste</h2><ul><li><strong>Vídeň</strong> – Hofburg palác, St. Stephens katedrála</li><li><strong>Salzburg</strong> – rodné město Mozarta</li><li><strong>Innsbruck</strong> – lyžařský ráj</li><li><strong>Hallstatt</strong> – nejkrásnější vesnice na světě</li><li><strong>Alpy</strong> – Dachstein a Hohe Tauern</li></ul><h2>Gastronomie</h2><ol><li><strong>Wiener Schnitzel</strong> – řízek vídeňský</li><li><strong>Sachertorte</strong> – čokoládový dort</li><li><strong>Kaiserschmarrn</strong> – trhané lívance</li><li><strong>Strudel</strong> – zavináč s jablkem</li></ol><p>Navštívit Rakousko znamená <strong>zdržet se v hudbě, architektuře a gastronomii</strong>!</p>', '2025-09-03');
